### ISSUE TITLE
tabulizer is not available (for R version 3.3.2)

### ISSUE THREAD

**Issue by kiranhsgithub** [ropensci/tabulizer#44]
I tried installing this R package and it gave below error.

Installing package into ‘C:/Users/hskir/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
Warning in install.packages :
package ‘tabulizer’ is not available (for R version 3.3.2)

May I know which version is supported. Thanks

**Comment by leeper** [comment]
It is not on CRAN. You have to install using `ghit::install_github("ropensci/tabulizer")` or `devtools::install_github("ropensci/tabulizer")`

**Comment by NikkiPDX15** [comment]
Having trouble installing tabulizer with the above suggestion. still shows as NA at the bottom of screen after attempt to install

**Comment by leeper** [comment]
@NikkiPDX15 Please try all suggestions listed here: https://ropensci.org/blog/blog/2017/04/18/tabulizer If none of those work, please add your `sessionInfo()` output and the complete installation code and output from `ghit::install_github("ropensci/tabulizer", verbose = TRUE)` installation attempt to the issue here: https://github.com/ropensci/tabulizer/issues/46
