### ISSUE TITLE
Handling issues related to upgrade to PDFBox 2.0

### ISSUE THREAD

**Issue by leeper** [ropensci/tabulizer#48]
The [tabula-java library is moving to PDFBox 2.0](https://github.com/tabulapdf/tabula-java/issues/52), which will have consequences not only for the tabula API but also for some of the utility functions that tabulizer implements by calling PDFBox classes directly. This is flagged as [an issue at tabulizerjars](https://github.com/ropensci/tabulizerjars/issues/3) and will likely have numerous consequences for tabulizer. Any help identifying and correcting this issues will be appreciated.

**Comment by leeper** [comment]
tabulizerjars has been updated ([on a branch](https://github.com/ropensci/tabulizerjars/tree/tabula1.0.0)) to 1.0.0

**Comment by tpaskhalis** [comment]
Thank you for a great package! I did some work on migration to PDFBox 2.0. The changes are [here](https://github.com/tpaskhalis/tabulizer/commit/d848d40aab7a0d5e4cd1bd94dd6be5b86f074972). I have some trouble with setting resolution in [make_thumbnail.R](https://github.com/tpaskhalis/tabulizer/blob/pdfbox2.0/R/make_thumbnails.R#L53-L54) through [renderImageWithDPI](https://pdfbox.apache.org/docs/2.0.7/javadocs/org/apache/pdfbox/rendering/PDFRenderer.html#renderImageWithDPI(int,%20float)), but otherwise everything seems to work.

**Comment by leeper** [comment]
Hey that's great! Is that using the latest tabulizerjars?

**Comment by tpaskhalis** [comment]
Yes, it's based on `tabula 1.0.1` from the branch of tabulizerjars.

**Comment by tpaskhalis** [comment]
I did further work on the migration and feature development. The problem with resolution in thumbnails has been fixed. Added some new functionality, such as extracting text by area and separated out coordinates conversion: [pdfbox2.0](https://github.com/tpaskhalis/tabulizer/commits/pdfbox2.0). My next goal is implementing `stream` option from #65

**Comment by tpaskhalis** [comment]
I think #83 resolves this. So, maybe we could close it and then open separate issues for individual problems if they emerge.

**Comment by leeper** [comment]
Great. I'm happy to have you close this then.

**Comment by tpaskhalis** [comment]
Ok, great! I'm closing it.
